# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e917f91be490763dfa324132861db593"
application_url = "https://kuwait-sum-examinations-make.trycloudflare.com"
embedded = true
name = "Stock Smart"
handle = "stock-smart-1"

[build]
include_config_on_deploy = true
dev_store_url = "store-for-customer-account-test.myshopify.com"
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2024-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_inventory,read_locations,write_inventory,write_products"

[auth]
redirect_urls = [
  "https://kuwait-sum-examinations-make.trycloudflare.com/auth/callback",
  "https://kuwait-sum-examinations-make.trycloudflare.com/auth/shopify/callback",
  "https://kuwait-sum-examinations-make.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
