# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a6f7886077bea7e16b6f1614edcff9e7"
application_url = "https://modifications-ul-evaluating-chancellor.trycloudflare.com"
embedded = true
name = "multi-store-inventory-app"
handle = "multi-store-inventory-app"

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://modifications-ul-evaluating-chancellor.trycloudflare.com/auth/callback",
  "https://modifications-ul-evaluating-chancellor.trycloudflare.com/auth/shopify/callback",
  "https://modifications-ul-evaluating-chancellor.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "store-for-customer-account-test.myshopify.com"
automatically_update_urls_on_dev = true
